### ISSUE TITLE
ops instance create port parameter seems to be ignored

### ISSUE THREAD

**Issue by Dmitry-N-Medvedev** [nanovms/ops-examples#45]
hi,

the context:

```bash
ops instance create -i service.authswitch.img -t onprem -p 6379
```

```bash
booting service.authswitch.img ...
```

```bash
ops instance list -t onprem -z onprem
```

```bash
+-------+----------------------------------------------------------+---------+--------------------------------+-------------+------+
|  PID  |                           NAME                           | STATUS  |            CREATED             | PRIVATE IPS | PORT |
+-------+----------------------------------------------------------+---------+--------------------------------+-------------+------+
| 58178 | /Users/dmitrymedvedev/.ops/images/service.authswitch.img | Running | 2020-05-14 00:18:34.723467212  | 127.0.0.1   | 8080 |
|       |                                                          |         | +0200 CEST                     |             |      |
+-------+----------------------------------------------------------+---------+--------------------------------+-------------+------+
```

As you can see, the PORT reported is **8080**, whereas the expected port was the **6379**.

**NB**: The **service.authswitch.img** image contains a NodeJS code that should connect to a Redis database which resides on the host.

What am I doing wrong to open the **6379**? Do I have to open this port at all to have the unikernel be able to connect to an external Redis database?

**Comment by eyberg** [comment]
this pops open the redis server on 6379

```
ops load -p 6379 redis_5.0.5
```

and you should be able to connect to it via telnet to verify

```
telnet 127.0.0.1 6379
```

you need to do that for incoming ports but not outgoing ones

your client doesn't actually need any port opened (if all it is a client) since it's outgoing vs incoming and in fact you shouldn't cause the port can only be bound to one instance

so after running the server you should be able to just run 

```
ops instance create -i service.authswitch.img -t onprem
```

the onprem targets aren't fully baked yet as no one really was using them but it looks like in this case the ```ops instance list``` for onprem is stubbed to show 8080 even though it pops the right port - you can verify that through ps

```
ps aux | grep qemu
```

https://github.com/nanovms/ops/issues/518

as an aside if you see a bug/feature definitely feel free to open on the ops repo - https://github.com/nanovms/ops

**Comment by eyberg** [comment]
closing since stub was removed https://github.com/nanovms/ops/pull/520
